//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Resources.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Resources.Errors.ValidationErrors", typeof(ValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match..
        /// </summary>
        public static string ConfirmationPasswordMatch {
            get {
                return ResourceManager.GetString("ConfirmationPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid first name format. First name must meet the following criteria:
        ///&lt;ul&gt; &lt;li&gt;Start with a capital letter (including Estonian characters: Ä, Ö, Ü, Õ, Š, Ž).&lt;/li&gt; &lt;li&gt;Contain only lowercase letters after the first (ä, ö, ü, õ, š, ž, and Latin letters a–z).&lt;/li&gt; &lt;li&gt;Can include a hyphen (`-`) or a space (` `), but not both together.&lt;/li&gt; &lt;li&gt;Each part of the first name after a separator must start with a capital letter.&lt;/li&gt; &lt;li&gt;No digits, special characters, or consecutive spaces/hyphens are allowed.&lt;/li [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FirstnameRegex {
            get {
                return ResourceManager.GetString("FirstnameRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; field is not a valid email address..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid last name format. Last Name must meet the following criteria:
        ///&lt;ul&gt; &lt;li&gt;Start with a capital letter (including Estonian characters: Ä, Ö, Ü, Õ, Š, Ž).&lt;/li&gt; &lt;li&gt;Contain only lowercase letters after the first (ä, ö, ü, õ, š, ž, and Latin letters a–z).&lt;/li&gt; &lt;li&gt;No hyphens, spaces, digits, or special characters are allowed.&lt;/li&gt; &lt;/ul&gt;.
        /// </summary>
        public static string LastnameRegex {
            get {
                return ResourceManager.GetString("LastnameRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of field &apos;{0}&apos; must not be greater than {1} symbols..
        /// </summary>
        public static string MaxLengthValidationError {
            get {
                return ResourceManager.GetString("MaxLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum length of field &apos;{0}&apos; must not be less than {1} symbols..
        /// </summary>
        public static string MinLenghtValidationError {
            get {
                return ResourceManager.GetString("MinLenghtValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; field is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string StringLengthBetween {
            get {
                return ResourceManager.GetString("StringLengthBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username format. Usernames must meet the following criteria:
        ///
        ///                &lt;ul&gt;
        ///                    &lt;li&gt;Begin with a letter or a digit.&lt;/li&gt;
        ///                    &lt;li&gt;Can contain letters, digits, periods (.), or underscores (_).&lt;/li&gt;
        ///                    &lt;li&gt;Cannot contain two consecutive periods (.) or underscores (_).&lt;/li&gt;
        ///                    &lt;li&gt;End with a letter or a digit.&lt;/li&gt;
        ///                &lt;/ul&gt;.
        /// </summary>
        public static string UsernameRegex {
            get {
                return ResourceManager.GetString("UsernameRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; must be between {1} and {2}..
        /// </summary>
        public static string ValueBetween {
            get {
                return ResourceManager.GetString("ValueBetween", resourceCulture);
            }
        }
    }
}
