"use client";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { AccountContext, IAccountInfo } from "@/context/AccountContext";
import { useEffect, useState } from "react";
import { getRolesFromToken, getUserIdFromToken, getUsernameFromToken } from "@/helpers/JwtHelper";
import Spinner from "@/components/LoadingSpinner";
import "../../i18n";

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const [accountInfo, setAccountInfo] = useState<IAccountInfo | undefined>();
	const [hydrated, setHydrated] = useState(false); // For hydration check

	useEffect(() => {
		const jwt = localStorage.getItem("_jwt");
		const refreshToken = localStorage.getItem("_refreshToken");

		if (jwt && refreshToken) {
			setAccountInfo({
				jwt,
				refreshToken,
				roles: getRolesFromToken(jwt),
				name: getUsernameFromToken(jwt),
				id: getUserIdFromToken(jwt)
			});
		} else {
			setAccountInfo({}); // ensures logout is reflected
		}

		setHydrated(true); // Mark hydrated
	}, [hydrated]);

	const updateAccountInfo = (value: IAccountInfo) => {
		setAccountInfo(value);
		if (value?.jwt && value?.refreshToken) {
			localStorage.setItem("_jwt", value.jwt);
			localStorage.setItem("_refreshToken", value.refreshToken);
		} else {
			localStorage.removeItem("_jwt");
			localStorage.removeItem("_refreshToken");
		}
	};

	return (
		<html lang="en">
			<body>
				{!hydrated ? (<Spinner className="h-64" />) : (
					<AccountContext.Provider
						value={{
							accountInfo: accountInfo,
							setAccountInfo: updateAccountInfo,
						}}
					>
						<Header />
						<div className="px-4 mx-auto max-w-7xl">
							<main role="main" className="w-full text-center">
								{children}
							</main>
						</div>
						<Footer />
					</AccountContext.Provider>
				)}
			</body>
		</html>
	);
}
